# Generated by django-supchat maintainers
import django
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_online", models.BooleanField(db_index=True, default=False)),
                ("last_seen", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="supchat_operator", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["user__username"]},
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("guest_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("closed", "Closed")], db_index=True, default="open", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_message_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("assigned_operator", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="conversations", to="supchat.operator")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="supchat_conversations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-last_message_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sender_type", models.CharField(choices=[("user", "User"), ("guest", "Guest"), ("operator", "Operator"), ("system", "System")], db_index=True, max_length=16)),
                ("text", models.TextField()),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="supchat.conversation")),
                ("sender_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="supchat_messages", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AddIndex(model_name="operator", index=models.Index(fields=["is_online", "last_seen"], name="supchat_ope_is_onli_4c1f6a_idx")),
        migrations.AddIndex(model_name="conversation", index=models.Index(fields=["status", "last_message_at"], name="supchat_con_status_07f83d_idx")),
        migrations.AddIndex(model_name="conversation", index=models.Index(fields=["user", "status"], name="supchat_con_user_id_06e29d_idx")),
        migrations.AddIndex(model_name="conversation", index=models.Index(fields=["guest_id", "status"], name="supchat_con_guest_i_4321c7_idx")),
        migrations.AddIndex(model_name="conversation", index=models.Index(fields=["assigned_operator", "status"], name="supchat_con_assigne_43c7ba_idx")),
        migrations.AddIndex(model_name="message", index=models.Index(fields=["conversation", "created_at"], name="supchat_mes_convers_c92c05_idx")),
        migrations.AddIndex(model_name="message", index=models.Index(fields=["conversation", "is_read"], name="supchat_mes_convers_d9732d_idx")),
        migrations.AddIndex(model_name="message", index=models.Index(fields=["sender_type", "created_at"], name="supchat_mes_sender__a73e2c_idx")),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                **({"condition": models.Q(("user__isnull", False), ("guest_id__isnull", False), _connector="OR")} if django.VERSION >= (5, 1) else {"check": models.Q(("user__isnull", False), ("guest_id__isnull", False), _connector="OR")}),
                name="supchat_conversation_has_participant",
            ),
        ),
    ]
